pipeline_output : "/srv/nfs/ngs-stockage/NGS_Virologie/HadrienR/DATASET/"
adapter1 : "AATGATACGGCGACCACCGAGATCTACACXXXXXXXXACACTCTTTCCCTACACGACGCTCTTCCGATC*T"
adapter2 : "CAAGCAGAAGACGGCATACGAGATXXXXXXXXGTGACTGGAGTTCAGACGTGTGCTCTTCCGATC*T"
